apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-multiple-sources
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/TejaswiniOpsmx/appset.git'
        revision: HEAD
        directories:
          - path: appse
          - path: set-apps
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/TejaswiniOpsmx/appset.git'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
